import "./globals.css";
import dbConnect from "@/lib/dbConnect";

export const metadata = {
  title: "Subirana Nandons",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  await dbConnect();
  console.log("MongoDB connected to layout");
  return (
    <html lang="en">
      <body
        className="w-full overflow-x-hidden">
        {children} 
      </body>
    </html>
  );
}