import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
 
export const metadata = {
  title: "Subirana Nandons",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="w-full overflow-x-hidden"
      >
        {children}
      </body>
    </html>
  );
}
